exclude: [Makefile]

collections:
    songs:
      output: true

defaults:
  - scope:
      path: ""
      type: "songs"
    values:
      layout: "song"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: /blog/:categories/:year/:month/:day/:title
  - scope:
      path: ""
    values:
      layout: "page"
