baseurl: "https://knaveightt.github.io/totalknavery"

collections:
    songs:
      output: true

defaults:
  - scope:
      path: ""
      type: "songs"
    values:
      layout: "song"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "page"
